CFLAGS = -Wall

all: parent_and_child

parent_and_child:
	gcc $(CFLAGS) parent_and_child.c -o parent_and_child
	

clean:
	rm -f parent_and_child


test:
	./parent_and_child /mnt/c/Users/Magda/Desktop/studia/IVSEM/SysOpy/lab4/zad1
	./parent_and_child aaa
	