CXX = gcc
CFLAGS = -Wall -g -o 

####################### Targets beginning here #########################

all: countdown

# Builds the app
countdown: 
	$(CXX) $(CFLAGS) countdown countdown.c

# Cleans binary files
.PHONY: clean
clean:
	rm countdown

