CFLAGS = -Wall -std=gnu99

all: main calculate_integral

main:
	gcc $(CFLAGS) main.c -o main

calculate_integral:
	gcc $(CFLAGS) calculate_integral.c -o calculate_integral


clean:
	rm -f main
	rm -f calculate_integral


run_calc:
	./calculate_integral


test:
	./main
	
	
