CFLAGS = -Wall -std=gnu99

all: catcher sender

catcher:
	gcc $(CFLAGS) catcher.c -o catcher

sender:
	gcc $(CFLAGS) sender.c -o sender

clean:
	rm -f catcher
	rm -f sender

run_catcher:
	./catcher

	
	
	
	
